include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: true
    require_trailing_commas: true
